# Site settings
baseurl = "https://nmonhait.github.io/csu_rcollab/" # what is your website's url? 
canonifyurls = true
relativeurls = true
languageCode = "en-us"
title = "Colorado R Collab" # what is your conference called? 
location = "Fort Collins, CO" # When and where is your conference?
theme = "hugo-ropensci-theme"
publishDir = "public"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-36719749-4" 

[params]
  # To provide some metadata for search engines feel free to add a few
  # information about you and your website.
  name = "Colorado R Collab" # What is your conference called? 
  description = "Colorado State University, April 2-3, 2020" # Where is your conference? What are the dates? 

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []

  # Possibility to disable external/additional fonts
  # Exception: Fontawesome
  disableFonts = false

  # 404 error customization
  [params.error404]
    heading = "Sorry, but you seem to have become lost."
    text = "Please visit [the front page](/)"

  # Optional piwik tracking
  #[params.analytics.piwik]
  #  URL = "https://stats.example.com"
  #  ID = "42"
  #  # Track all subdomains with "*.example.com"
  #  domain = "www.example.com"
  #  # Optional integrity check hash
  #  hash = "sha512-RfeD0pacGTqy9m7U6PgehQfS4cc7SIt+e+P+H5e848kEvB/RW84CUGO3O4O3LNbxjevym6KPUZ8muPsMrI8WIw=="

  # Navigation
  [params.navigation]
#    brand = "FIXME" # Your organization/company/school that is hosting the conf. Or just your unconf's name
    logo = "corcollab_logo.png" # Your brand logo stored in img/
    about = "What"  # These are the header links.  
    team = "Who"
    joinus="Join Us"
    venue = "Venue"
    #sponsors = "Sponsors"
    contact = "Contact"

    # Add custom links. Those can be pre- and postpended to the default menu above.
    # Use the weight attribute to order your custom links. Uncomment the example
    # below and replace the values with your own.

    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10


  # Hero section
  [params.hero]
    # To change the background image of the hero, replace 'header-bg.jpg' in
    # the 'static/img' folder.
    title = "Colorado R Collab" # Your unconf's name here 
    subtitle = "April 2--3, 2020 • Fort Collins • Colorado" #Date, City, State/Country
    # buttonText = "Tell me more"


   # About section
   [params.about]
    enable = true
    title = "About the Colorado R Collab" # What is your unconference called, again? 
    # In the text section below, describe your event. What makes your event special? Where it says FIXME, substitute your unconf's name
    text = "The Colorado R Collaborative is part of an [R Consortium-funded grant](https://www.r-consortium.org/projects/awarded-projects) that supports community-led, locally-organized R development events around the world, otherwise known as R Community Collaboratives.\n\n At the Colorado R Collab, you'll team up with R users and developers of all skill levels. Together, you will create a valuable data product that will contribute directly to a research team at Colorado State University. \n\n This year's theme will be **Sports and Movement**, and participants at the event will work on developing R code and methods to explore and analyze data on this topic contributed by researchers from Colorado State University. Whether you are an experienced developer or an R-user-to-be, you have something to contribute to this event. Our event is open to a wide range of experience levels and attendee backgrounds, and we seek to encourage diverse groups to contribute to the larger R community. \n\n If you’re interested in learning more about what you’ll be doing at the event, take a look at the schedule for other R Collaborative events, including [last year's Chicago R Collaborative](https://github.com/chirunconf/chirunconf19/wiki/Schedule), peruse our [Code of Conduct](https://nmonhait.github.io/csu_rcollab/coc), or reach out to corcollab [at] gmail.com if you have questions!   "


  # Team section
  [params.team]
    enable = true
    # Possibility to center items
    #center = true
    title = "Organizers"
    # How would you describe your participants? What are they bringing to your event
    text = "Our team is dedicated to inspiring beginners and those new to open source to contribute to the R community. We’ve worked in industry and academia alike, and we believe that open source is at its best when it draws from diverse contributors."

    # All team member's pictures should be stored under 'static/img/team'.
    # Suggestion: Image size should be at least 360px*360px or the alignment might be affected.
    
    [[params.team.members]] # create one of these for each of your participants
      name = "Nichole Monhait" 
      position = "RStudio"
      img = "nrm.JPG" # e.g. firstname-lastname.png 
      twitter = "@nrmonhait" # handle only. (not a URL, no @)
      github = "github.com/nmonhait" # handle only. (not a URL, no @)
      
    [[params.team.members]]
      name = "Brooke Anderson"
      position = "Colorado State University"
      img = "gba.jpg"
      twitter = "@gbwanderson"
      github = "github.com/geanders"
    
    [[params.team.members]] # create one of these for each of your participants
      name = "Molly Gutilla"
      position = "Colorado State University"
      img = "avatar.jpg" # e.g. firstname-lastname.png ("avatar.jpg" is default)
#      twitter = "twitterhandle" # handle only. (not a URL, no @)
#      github = "githubhandle" # handle only. (not a URL, no @)
#      url = "website" # A URL 
      
# Join us section
  [params.joinus]
  enable=true
  title = "Join us!"
  # describe how your event will take in participants. 
  text = "Applications for the For Collins R Collab are open! The [application form](https://docs.google.com/forms/d/e/1FAIpQLScSgzq-ZR5P9d6kZPf8pzhqgz612aSI-XqDmtZ5-OruzuiIGA/viewform?usp=sf_link) should take around 15--20 minutes to fill out and will help us gauge your interest and involvement in the R community. The deadline for applications is midnight MST on March 6, 2020 and we plan to notify participants by March 13, 2020."

# Venue section  
  [params.venue]
  enable=true
  title = "Venue"
  text = "The event will be hosted at Colorado State University in the Outreach Classroom (H210 AZ)."
  map = "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3030.7194139143517!2d-105.0849376845994!3d40.569873079347495!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x87694a54460c4bd1%3A0x1256e5725a6b2df3!2sAnatomy%20-%20Zoology%2C%201350%20Center%20Ave%2C%20Fort%20Collins%2C%20CO%2080521!5e0!3m2!1sen!2sus!4v1581959273510!5m2!1sen!2" # Link to a Google map embed of your venue's location. Visit https://support.google.com/maps/answer/144361?co=GENIE.Platform%3DDesktop&hl=en to see how to Embed a Google map
  img = "venue.jpg" # An image of your venue in the static/img folder
  # Sponsors section

#    [params.sponsors_list]
#      enable = true
      # Possibility to center items
      #center = true
#      title = "Sponsors"
#      text = "We are extremely grateful to all the sponsors for this year's event. If your organization would like to sponsor FIXME, please email FIXME for a sponsorship prospectus."

      # All the sponsors' logos are stored under 'static/img/sponsors'.
      # Replace them with your sponsors's logos.
      # Suggestion: .svg in the size of 280px*80px looks good
      
#      [[params.sponsors]] # create one of these for each of your sponsors. 
#        logo = "coke.png"  # file in static/img/sponsors
#        link = "https://us.coca-cola.com/" # url of the sponsor 

  # Footer section
  [params.footer]
    enable = true
    copyright = "Published under the Apache License 2.0."
    text = "[Contact us](mailto:corcollab@gmail.com) for more information about the event. Because we want to make sure everyone has a safe and comfortable experience, this event follows a [code of conduct](https://nmonhait.github.io/csu_rcollab/coc). This page is available at [this repo](https://github.com/nmonhait/csu_rcollab). Corrections, changes, and suggestions for improvement are welcome as pull requests."

# Not used
 #   [[params.footer.quicklinks]]
#      text = "Privacy Policy"
#      link = "#"
# Not used
#    [[params.footer.quicklinks]]
#      text = "Terms of Use"
#      link = "#"
      
  # OPTIONAL: Contact section. (Will go above the footer.) Uses an external service to have a contact for on the website. 
  # uncomment the [params.contact] section to use. 
  #[params.contact]
  #  enable = false
  #  title = "Contact us"
  #  text  = "Lorem ipsum dolor sit amet consectetur."
  #  buttonText = "Send message"

    # INSTRUCTIONS TO SET UP THE CONTACT FORM: Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below (uncomment it first)
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!

    # It is possible to substitute formspring with other providers
    # as an example the mailout plugin from caddy.
    # Provide the post URL for the form and depending on the provider
    # add some custom JS script to finish the implementation.
    # postURL = "https://example.com/mailout/"

    #email = "nicholas.tierney@monash.edu"

    # Success and error message overwrite for async contact form
    #thanks = "Thank you for awesomely contacting us."
    #error = "Message could not be send. Please contact us at mail@example.com instead."

    # 'warning' defines error messages for invalid inputs
    # Uncomment to use contact form
  #  [params.contact.form.name]
   #   text = "Your Name *"
    #  warning = "Please enter your name."
  # Uncomment to use contact form
   # [params.contact.form.email]
  #    text = "Your Email *"
   #   warning = "Please enter your email address."
# Uncomment to use contact form
   # [params.contact.form.phone]
  #    text = "Your Phone *"
  #    warning = "Please enter your phone number."
# Uncomment to use contact form
    #[params.contact.form.message]
    #  text = "Your Message *"
    #  warning = "Please enter a message."
# Uncomment to use contact form
      # Add optional form fields to identify contact forms
      #[[params.contact.form.hidden]]
      #  name = "someID"
      #  value = "example.com"
# Uncomment to use contact form      
      #[[params.contact.form.hidden]]
      # Special values for name such as "page" and "site" will be autofilled
      #  name = "page"      
